import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import faq from './faq'
import gallery from './gallery'
import standards from './standards'
import stomatology from './stomatology'
import cosmetology from './cosmetology'
import team from './team'
import reviews from './reviews'
import promotion from './promotion'
import price from './price'

export const schemaTypes = [post, author, category, blockContent, faq, reviews, gallery, standards, stomatology, cosmetology, team, promotion, price];
